### PR TITLE
Using QueryCriteria for listing created IOUs by party

### PR DESCRIPTION
**Pull request by dineshrivankar**
New API endpoint created for listing all the IOU created by individual party

/api/example/my-ious

You can view all created IOU of a party by accessing the vault eg:  PartyA 

Via the HTTP API:
PartyA’s vault: Navigate to http://localhost:10009/api/example/my-ious

### CODE REVIEW

**Review by joeldudley — CHANGES_REQUESTED** [review]
Hi Dinesh, this isn't working for me. The HTTP endpoint works, but I don't see my IOUs on the page, just the recorded IOUs.

**Comment by dineshrivankar** [comment]
Hi @joeldudleyr3  Thanks for taking time to review this.
The UI element is an bootstrap accordion and we need to click on the header to see the records .... My bad 
image

Should we make it as normal HTML without bootstrap accordion ?

**Comment by joeldudley** [comment]
@dineshrivankar Yes, I think making it normal HTML instead of an accordion would be best. I didn't even realise I should click :)

**Comment by dineshrivankar** [comment]
@joeldudleyr3 I have removed the bootstrap accordion.Kindly review.

**Review by joeldudley — APPROVED** [review]

**Comment by joeldudley** [comment]
@dineshrivankar Hi Dinesh. Because this contribution is part of the Corda GitHub organisation, I need to check whether your contribution is in accordance with the Developer's Certificate of Origin - see https://github.com/corda/corda/blob/master/CONTRIBUTING.md#developer-certificate-of-origin.

If it is, can you leave a comment stating that “I hereby certify that my contribution is in accordance with the Developer Certificate of Origin (https://github.com/corda/corda/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).”

**Comment by dineshrivankar** [comment]
I hereby certify that my contribution is in accordance with the Developer Certificate of Origin

**Pull request merged**
