### PR TITLE
Updated to use new Vault Query Service API.

### PR DESCRIPTION
**Pull request by josecoll**
Minor updates to use Vault Query snapshot API.

### CODE REVIEW

**Comment by josecoll** [comment]
Imports shouldn't churn that much if you consistently use IntelliJ "Optimize imports" (generally they are grouped).

**Comment by josecoll** [comment]
Will update to IOUState.

**Comment by joeldudleyr3** [comment]
We must have different IntelliJ `optimize import` settings. Mine would never import the entirety of `org.bouncycastle.asn1.x500` just to get `X500Name`.

**Comment by josecoll** [comment]
A couple of minor changes to reflect following PR:
https://github.com/corda/corda/pull/914

**Pull request merged**
