### PR TITLE
Migrate web API to Java Spring client server 

### PR DESCRIPTION
**Pull request by mcevoyinit**
This PR is to migrate from the Jetty webserver example API to a standalone Java Spring example API that connects to the node remotely via RPC.

- All changes exist within the a new clients module configured in setting.gradle
- Added NodeRPCConnection.kt client, Server.kt that defines the Springboot application and a MainController.kt holds the IOU API.
- Added 3 tasks to build.gradle to start-up 3 isolated spring servers for each Party.
- resources/public/angular-module.js and index.html that define the cordapps frontend in which each server has its own instance of.

This can be tested by running each server tasks and navigating to localhost ports 8080, 8081 and 8082
Could you confirm it is now okay to remove any instances of the jetty api in the sample?

### CODE REVIEW

**Comment by mcevoyinit** [comment]
Just a note on a checklist for removing remnants of the jetty API.
- com.example.api for java-source and kotlin-source
- their corresponding resource folders
- remove webport instances from their build.gradles so webserver jars dont appear in node folders

Should that be everything?
Cheers

**Comment by mcevoyinit** [comment]
@joeldudleyr3 I don't think I have permissions to assigned a reviewer here?

**Comment by joeldudley** [comment]
Hey Eric, would you be able to raise the PR against github.com/corda/samples instead? We’re supposed to be pointing people to that now, we just haven’t had time to announce it.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by mcevoyinit** [comment]
Sure thing, I don't see what I will merge into since the cordapp-example isn't within the corda/samples folder. Will I leave the clients as it's own module there? It's coupled to the IOU example though.

**Comment by joeldudley** [comment]
I mean github.com/corda/samples - it’s a repo with all the samples to make mass updates easier (eg Cordform changes). :)

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Pull request closed without merging**
